### ISSUE TITLE
Unable to init InitializeResult.Failure on my unit test with the last version 2.2.20

### ISSUE THREAD

**Issue by anismarzouk808** [Adyen/adyen-3ds2-android#72] opened 2024-09-10 08:44 UTC
**Describe the bug**
 When trying to update the sdk version to 2.2.20 ; I have a unit test for the failure useCase , it start failing due to the use of  System.loadLibrary() call on almost every init block of your API surface.

**To Reproduce**
   We have a java.lang.UnsatisfiedLinkError when trying to initialize the failure ;
   
   `val failedInitialize = InitializeResult.Failure(
            transactionStatus = Random.nextString(10),
            additionalDetails = Random.nextString(10),
        )`

**Expected behavior**
We didn't have this issue with the previous versions

**Comment by fdcb** [comment] 2024-09-11 08:24
Hey @anismarzouk808 Thank you for reporting!
We will let you know once a version with a fix has been released.

**Comment by tkuntubayev** [comment] 2024-10-11 16:11
Hi @anismarzouk808,
The recently released 2.2.21 SDK version is built to allow SDK API classes initialization from Unit tests. Please let us know if the issue is resolved.

**Comment by tkuntubayev** [comment] 2024-11-14 10:34
Closing due to inactivity. Please feel free to reopen if the issue persist after the update.

**Closed by tkuntubayev** 2024-11-14 10:34 UTC
Labels: bug
