### ISSUE TITLE
ChallengeActivity is crashing on inflation

### ISSUE THREAD

**Issue by Ajibola** [Adyen/adyen-3ds2-android#1] opened 2018-12-04 14:06 UTC
I am getting an exception when trying to call doChallenge on the transaction due to the error below : 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mttnow.droid.easyjetStag/com.adyen.threeds2.internal.ui.activity.ChallengeActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.adyen.threeds2.internal.ui.view.ToolbarView

I can send a longer stack trace if neded.

**Comment by ran-haveshush** [comment] 2019-01-24 09:04
Hi @Ajibola,

Can you check if the issue persists on the latest version 0.9.2?

**Comment by Ajibola** [comment] 2019-01-25 13:07
Hi @ran-haveshush thanks for getting back, I have tested the latest SDK version and the issue still persists. Still blocked by the doChallenge step while inflating the ToolbarView.

**Comment by ran-haveshush** [comment] 2019-01-25 13:47
Hi @Ajibola thank you for reporting the issue.

Can you provide the entire stack trace?

**Comment by Ajibola** [comment] 2019-01-28 13:03
2019-01-28 13:00:05.132 9353-9353/com.mttnow.droid.appStag E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mttnow.droid.appStag, PID: 9353
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mttnow.droid.appStag/com.adyen.threeds2.internal.ui.activity.ChallengeActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.adyen.threeds2.internal.ui.view.ToolbarView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.adyen.threeds2.internal.ui.view.ToolbarView
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.adyen.threeds2.internal.ui.view.ToolbarView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.adyen.threeds2.internal.ui.view.c.onCreateView(Unknown Source:15)
        at com.adyen.threeds2.internal.ui.activity.b.onCreateView(Unknown Source:2)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreateView(Unknown Source:0)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:23257)
        at com.adyen.threeds2.internal.ui.view.ChallengeView.<init>(Unknown Source:5)
        at com.adyen.threeds2.internal.ui.view.a.<init>(Unknown Source:0)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:0)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:1)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:1)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:87)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:24)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreate(Unknown Source:7)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
2019-01-28 13:00:05.137 9353-9353/com.mttnow.droid.appStag E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.adyen.threeds2.internal.ui.view.c.onCreateView(Unknown Source:63)
        at com.adyen.threeds2.internal.ui.activity.b.onCreateView(Unknown Source:2)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreateView(Unknown Source:0)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:23257)
        at com.adyen.threeds2.internal.ui.view.ToolbarView.<init>(Unknown Source:5)
        at com.adyen.threeds2.internal.ui.view.ToolbarView.<init>(Unknown Source:1)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.adyen.threeds2.internal.ui.view.c.onCreateView(Unknown Source:15)
        at com.adyen.threeds2.internal.ui.activity.b.onCreateView(Unknown Source:2)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreateView(Unknown Source:0)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:23257)
        at com.adyen.threeds2.internal.ui.view.ChallengeView.<init>(Unknown Source:5)
        at com.adyen.threeds2.internal.ui.view.a.<init>(Unknown Source:0)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:0)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:1)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:1)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:87)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:24)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreate(Unknown Source:7)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0400be a=3}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.view.View.<init>(View.java:4771)
        at android.view.ViewGroup.<init>(ViewGroup.java:597)

**Comment by ran-haveshush** [comment] 2019-01-30 08:00
@Ajibola your are using an older version of the library,
Can you share how you import the library into your module?

**Comment by Ajibola** [comment] 2019-01-31 16:00
@ran-haveshush you were right, but with the new lib a similar issue persists. 

2019-01-31 15:43:52.325 3454-3454/com.mttnow.droid.appStag E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mttnow.droid.appStag, PID: 3454
    android.view.InflateException: Binary XML file line #124: Binary XML file line #124: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #124: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:23257)
        at com.adyen.threeds2.internal.ui.view.ChallengeView.<init>(Unknown Source:50)
        at com.adyen.threeds2.internal.ui.view.a.<init>(Unknown Source:70)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:49)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:45)
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:41)
        at com.adyen.threeds2.internal.ui.activity.a.a(Unknown Source:104)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:236)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent(Unknown Source:117)
        at android.app.Activity.performNewIntent(Activity.java:7044)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1331)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1343)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3023)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3039)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3055)
        at android.app.ActivityThread.-wrap14(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0400be a=3}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
        at android.widget.TextView.<init>(TextView.java:1214)
        at android.widget.Button.<init>(Button.java:166)
        at android.widget.Button.<init>(Button.java:141)
        at android.widget.Button.<init>(Button.java:117)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.view.View.inflate(View.java:23257) 
        at com.adyen.threeds2.internal.ui.view.ChallengeView.<init>(Unknown Source:50) 
        at com.adyen.threeds2.internal.ui.view.a.<init>(Unknown Source:70) 
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:49) 
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:45) 
        at com.adyen.threeds2.internal.ui.view.TextChallengeView.<init>(Unknown Source:41) 
        at com.adyen.threeds2.internal.ui.activity.a.a(Unknown Source:104) 
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(Unknown Source:236) 
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent(Unknown Source:117) 
        at android.app.Activity.performNewIntent(Activity.java:7044) 
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1331) 
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1343) 
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3023) 
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3039) 
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3055) 
        at android.app.ActivityThread.-wrap14(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
2019-01-31 15:43:53.232 1910-7469/? W/ActivityManager:   Force finishing activity com.mttnow.droid.appStag/com.adyen.threeds2.internal.ui.activity.ChallengeActivity

**Comment by ran-haveshush** [comment] 2019-02-01 09:21
@Ajibola thanks for sending an updated stack trace.

Based on the stack trace, there is a missing attribute, we suspect it is the colorPrimary.
Without a sample that reproduces the issue it will be very hard for us to detect and fix the issue.

Can you please provide us a sample project that reproduce the issue?

**Comment by Ajibola** [comment] 2019-02-18 12:33
@ran-haveshush it seems this issue is resolved by having a theme that inherits from an AppCompat theme with no action bar in our case. Can "AppTheme.ThreeDS2" inherit from the AppCompat theme in the SDK?

**Comment by ran-haveshush** [comment] 2019-02-18 13:26
@Ajibola thanks for investigating the reason for the issue, yes the SDK theme inherits the App's theme "AppTheme" like so: <style name="AppTheme.ThreeDS2">.

Now that reason for the issue is found and resolved can we close the issue?

**Comment by Ajibola** [comment] 2019-02-19 11:35
@ran-haveshush I am not sure the process, but this should be fixed on the SDK side, i.e. inheriting from app compat. A fix on the implementation side is messy and may not be the best for updates etc. What do you think about this?

**Comment by ran-haveshush** [comment] 2019-02-19 14:49
@Ajibola I didn't understand. What are you suggesting?
We inherit from the AppTheme so that the default theme will apply to the SDK UI by default.

**Comment by Ajibola** [comment] 2019-02-19 16:26
@ran-haveshush I am suggesting that the style is updated so AppTheme inherits from Theme.AppCompat.NoActionBar.

**Comment by ran-haveshush** [comment] 2019-02-20 07:01
@Ajibola this is up to the app to define AppTheme inherited style not the SDK.
The SDK just follows the AppTheme defined by the App module.

**Comment by Ajibola** [comment] 2019-02-20 10:54
@ran-haveshush to be clear the sdk requires every project to have an theme named "AppTheme". This is not called out anywhere and not every project has a theme named AppTheme! Can you please update the Readme to reflect this thanks.

**Comment by ran-haveshush** [comment] 2019-02-20 11:17
@Ajibola thanks for the suggestion, we will do so.
We will close this issue.

**Closed** 2019-02-20 11:18 UTC
